title: Socracan 2018
email: socracan@gmail.com
description: Socrates Canaries 2018

environment: production
url: https://socracan.es

markdown: kramdown

exclude:
  - "/vendor/"
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - "/node_modules/"